### ISSUE TITLE
gulp-crisper: ignoring relative path

### ISSUE THREAD

**Issue by dobrysmak** [PolymerLabs/crisper#7] opened 2015-06-26 12:26 UTC
When using without vulcanize.js gulp-crisper seams to ignore relative paths ex

```
return gulp
     .src('./app/**/*.html') // same with base option
     .pipe(crisper())
     .pipe(gulp.dest('./build/');
```
output

`./app/elements/list/list.html   ->  ./build/list.html`
`./app/tmpl/template.html       -> ./build/template.html`

**Comment by Scarygami** [comment] 2015-07-29 19:23
Encountered the same issue, the problem is this line in `gulp-crisper/index.js`

    path: path.join(file.base, filename)

file.base would be `./app` so the resulting file will have all path information in between lost.

Everything works as expected when you change the line like this

    path: path.join(path.dirname(file.path), filename)

Will send a PR to https://github.com/ragingwind/gulp-crisper later.

**Comment by Scarygami** [comment] 2015-07-29 21:57
PR sent: https://github.com/ragingwind/gulp-crisper/pull/3

If you want you can use my fork until the PR is merged and the new version published.

`npm install git+https://git@github.com/scarygami/gulp-crisper.git --save-dev`

**Comment by Scarygami** [comment] 2015-07-30 12:51
This is merged and published now. Should work correctly if you update to version 0.0.5 of gulp-crisper

**Comment by ebidel** [comment] 2015-08-24 16:35
Closing :)

**Closed by ebidel** 2015-08-24 16:35 UTC
