### ISSUE TITLE
Output of vulcanize and crisper on polymer app template causes RangeError

### ISSUE THREAD

**Issue by DavidBates** [PolymerLabs/crisper#3] opened 2015-06-02 14:56 UTC
Trying to use the provided app template mentioned during IO for polymer 1.0 found here https://developers.google.com/web/tools/polymer-starter-kit/ to be the basis of a chrome app I am working on. 
First try was to simply run crisper on the file, this led to csp errors since it looked like it didn't inline first. So I tried the command listed in the instructions to vulcanize and then crisper the output. 
`vulcanize index.html --inline-script | crisper --html start.html --js start.js`
This seamed to work until I launched the packaged app, chrome seemed to freeze for a long time and then I received this output (I understand the font failures and know how to fix them, it's the rest I worry about) : 

`GET chrome-extension://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic net::ERR_FAILED
start.html:637 GET chrome-extension://fonts.googleapis.com/css?family=Inconsolata:400,700 net::ERR_FAILED
start.js:2847 [custom-style::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [dom-template::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [dom-repeat::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [array-selector::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [dom-if::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [iron-media-query::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [iron-selector::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [iron-meta::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [iron-meta-query::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
start.js:2847 [iron-iconset-svg::_prepTemplate]: top-level Polymer template must not be a type-extension, found  Move inside simple <template>.
2start.js:2856 Uncaught RangeError: Maximum call stack size exceeded.Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401window.Polymer @ start.js:2350(anonymous function) @ start.js:11226(anonymous function) @ start.js:11490
start.html:2630 Resource interpreted as Document but transferred with MIME type text/css: "chrome-extension://pacpbgchohinmeipfgojlbdifeehegab/bower_components/paper-drawer-panel/paper-drawer-panel.css".
12start.js:2856 Uncaught RangeError: Maximum call stack size exceeded.Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401window.Polymer @ start.js:2350(anonymous function) @ start.js:11226(anonymous function) @ start.js:11490
start.html:3445 Resource interpreted as Document but transferred with MIME type text/css: "chrome-extension://pacpbgchohinmeipfgojlbdifeehegab/bower_components/paper-item/paper-item-shared.css".
1182start.js:2856 Uncaught RangeError: Maximum call stack size exceeded.Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401Polymer.Base._addFeature.instanceTemplate @ start.js:2856Polymer.Base._addFeature._stampTemplate @ start.js:2852Polymer.Base._addFeature._initFeatures @ start.js:6901Polymer.Base.createdCallback @ start.js:2401window.Polymer @ start.js:2350(anonymous function) @ start.js:11226(anonymous function) @ start.js:11490`

**Comment by azakus** [comment] 2015-06-12 21:46
Duplicate of https://github.com/Polymer/polymer/issues/1827

**Closed by azakus** 2015-06-12 21:46 UTC
